src/controllers/AuthItemChildController.php
<?php

namespace ticmakers\adm\controllers;

use Yii;
use ticmakers\core\base\Controller;
use yii\web\Response;
use ticmakers\adm\models\base\AuthItemChild;
use ticmakers\adm\models\searchs\AuthItemChild as AuthItemChildSearch;

/**
 * Controlador AuthItemChildController implementa las acciones para el CRUD de el modelo AuthItemChild.
 *
 * @package ticmakers/adm
 * @subpackage controllers
 * @category Controllers
 *
 * @property string $model Ruta del modelo principal.
 * @property string $searchModel Ruta del modelo para la búsqueda.
 *
 * @author Juan Sebastian Muñoz Reyes <sebastianmr302@gmail.com>
 * @copyright Copyright (c) 2019 Tic Makers S.A.S. 
 * @version 0.0.1
 * @since 2.0.0
 */
class AuthItemChildController extends Controller
{
    public $modelClass = AuthItemChild::class;
    public $searchModelClass = AuthItemChildSearch::class;

    /**
     * Registrar rutas 
     *   
     * @return array[] $response | listado de rutas actualizado 
     */
    public function actionAssign()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $items = Yii::$app->getRequest()->post('items', []);
        $parent = Yii::$app->request->post('parent');
        $model = Yii::createObject($this->modelClass);
        return $model->assignRoutesPermission($items, $parent);
    }

    /**
     * Remover rol(es) a un usuario y registrarlo
     * 
     * @param int $id | identificador del usuario  
     * @return array[] $response | listado de rutas actualizado 
     */
    public function actionRevoke()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $items = Yii::$app->getRequest()->post('items', []);
        $parent = Yii::$app->request->post('parent');
        $model = Yii::createObject($this->modelClass);
        return $model->revokeRoutesPermission($items, $parent);
    }
}

src/controllers/AuthItemController.php
<?php

namespace ticmakers\adm\controllers;

use Yii;
use ticmakers\core\base\Controller;

use yii\web\Response;
use ticmakers\adm\models\base\AuthItemChild;
use ticmakers\adm\models\base\AuthItem;
use ticmakers\adm\models\searchs\AuthItem as AuthItemSearch;

/**
 * Controlador AuthItemController implementa las acciones para el CRUD de el modelo AuthItem.
 *
 * @package ticmakers\adm
 * @subpackage controllers
 * @category Controllers
 *
 * @property string $model Ruta del modelo principal.
 * @property string $searchModel Ruta del modelo para la búsqueda.
 *
 * @author Juan Sebastian Muñoz Reyes <sebastianmr302@gmail.com>
 * @copyright Copyright (c) 2019 Tic Makers S.A.S. 
 * @version 0.0.1
 * @since 2.0.0
 */
class AuthItemController extends Controller
{
    public $modelClass = AuthItem::class;
    public $searchModelClass = AuthItemSearch::class;

    /**
     * Establecemos el tipo de permiso
     *
     * @param [type] $searchModel
     * @return void
     */
    public function beforeSearchIndex(&$searchModel)
    {
        $searchModel->type = AuthItem::TYPE_ROL;
    }

    /**
     * Permite visualizar el formulario para la creación de un registro
     * o realizar la validación de los datos enviados y crear el registro.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $model = Yii::createObject($this->modelClass);

        if ($model->load(Yii::$app->request->post())) {
            $model->type = 'ROL';
            if ($model->save()) {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($model->module->id, 'It was created successfully'));
                return $this->redirect(['update', 'id' => $model->primaryKey]);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($model->module->id, 'There was an error trying to create.'));
            }
        }

        return $this->render(
            'create',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * Permite visualizar el formulario de actualización de un registro
     * o realizar la validación y modificación del registro.
     *
     * @param integer $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelItems = [
            'available' => $model->getAvailableRoleItems($model->name),
            'assigned' => $model->getAssignedRoleItems($model->name)
        ];
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($model->module->id, 'It was updated successfully'));

                return $this->redirect(['index']);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($model->module->id, 'Ocurrió un error al intentar editar.'));
            }
        }

        return $this->render(
            'update',
            [
                'model' => $model,
                'modelItems' => $modelItems
            ]
        );
    }


      
     /**
     * Permite incativar un registro en el sistema
     *
     * @return void
     */
    public function actionDelete($id)
    {
        $modelObject = $this->findModel($id);
        $modelObject->{$this->modelClass::STATUS_COLUMN} = $this->modelClass::STATUS_INACTIVE;
        if ($modelObject->save(false, [$this->modelClass::STATUS_COLUMN])) {
            Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($modelObject->module->id, 'It was eliminated successfully.'));
        } else {
            Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($modelObject->module->id, 'There was an error trying to delete.'));
        }
        
        return $modelObject->type == $modelObject::TYPE_ROL ? $this->redirect('index') : $this->redirect('permission');
        
    }
    
    /**
     * Permite ativar un registro en el sistema
     *
     * @return void
     */
    public function actionRestore($id)
    {
        $modelObject = $this->findModel($id);
        $modelObject->{$this->modelClass::STATUS_COLUMN} = $this->modelClass::STATUS_ACTIVE;

        if ($modelObject->save(false, [$this->modelClass::STATUS_COLUMN])) {
            Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($modelObject->module->id, 'It was restored successfully.'));
        } else {
            Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($modelObject->module->id, 'There was an error trying to restore.'));
        }

        return $modelObject->type == $modelObject::TYPE_ROL ? $this->redirect('index') : $this->redirect('permission');
    }


    /**
     * Lista todos registros según el DataProvider.
     *
     * @return string
     */
    public function actionPermission()
    {
        $searchModel = Yii::createObject($this->searchModelClass);
        $searchModel->type = 'PER';
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render(
            'permissions/index',
            [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]
        );
    }
    /**
     * Permite visualizar el formulario para la creación de un permiso
     * o realizar la validación de los datos enviados y crear el registro.
     *
     * @return string|Response
     */
    public function actionCreatePermission()
    {
        $model = Yii::createObject($this->modelClass);
        if ($model->load(Yii::$app->request->post())) {
            $model->type = 'PER';
            if ($model->save()) {

                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($model->module->id, 'It was created successfully'));
                return $this->redirect(['auth-item/update-permission', 'id' => $model->primaryKey]);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($model->module->id, 'There was an error trying to create.'));
            }
        }

        return $this->render(
            'permissions/create',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * Permite visualizar el formulario de actualización de un registro
     * o realizar la validación y modificación del registro.
     *
     * @param integer $id
     * @return string|Response
     */
    public function actionUpdatePermission($id)
    {
        $model = $this->findModel($id);
        $modelRoutes = [
            'available' => $model->getAvailableRoutesPermission($model->name),
            'assigned' => $model->getAssignedRoutesPermission($model->name)
        ];
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($model->module->id, 'It was created successfully'));

                return $this->redirect(['auth-item/permission']);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($model->module->id, 'Ocurrió un error al intentar editar.'));
            }
        }

        return $this->render(
            'permissions/update',
            [
                'model' => $model,
                'modelRoutes' => $modelRoutes
            ]
        );
    }

    /**
     * Permite obtener el listado actualizado de rutas asignads y disponibles
     * 
     * 
     */
    public function actionRefresh()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $model = Yii::createObject($this->modelClass);
        $response = [
            'routes' => [
                'available' => $model->getAvailableRoutes(),
                'assigned' => $model->getAssignedRoutes()
            ]
        ];
        return $response;
    }
    /**
     * Permite visualizar el formulario de creación y asignación de rutas.     * 
     * 
     * 
     */
    public function actionRoutes()
    {
        $model = Yii::createObject($this->modelClass);
        $modelRoutes = [
            'available' => $model->getAvailableRoutes(),
            'assigned' => $model->getAssignedRoutes()
        ];
        Yii::$app->response->format = \yii\web\Response::FORMAT_HTML;
        return $this->render(
            'routes/_form',
            [
                'model' => $model,
                'modelRoutes' => $modelRoutes
            ]
        );
    }
    /**
     * Permite crear una nueva ruta
     * 
     * @return boolean
     */
    public function actionCreateRoute()
    {
        $route = Yii::$app->request->post('route');

        Yii::$app->response->format = Response::FORMAT_JSON;
        $response = [];
        $model = Yii::createObject($this->modelClass);

        $result = $model->createRoute($route);
        if ($result['status']) {
            $response = [
                'status' => true,
                'routes' => $result['routes'],
                'message' => Yii::t($model->module->id, $result['message'])
            ];
        } else {
            $response = [
                'status' => false,
                'message' => Yii::t($model->module->id, $result['message'])
            ];
        }
        return $response;
    }
    /**
     * Asigna los permisos o items seleccionados a determinado rol
     * 
     * @return array[]
     */
    public function actionAssign()
    {
        $modelAssign = Yii::createObject(AuthItemChild::class);
        Yii::$app->response->format = Response::FORMAT_JSON;
        $items = Yii::$app->getRequest()->post('items', []);
        $parent = Yii::$app->request->post('parent');
        return $modelAssign->assignItemsToRoles($items, $parent);
    }
    /**

src/views/auth-item/permissions/1_information.php
<?php

use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\YiiAsset;
use ticmakers\adm\models\base\AuthItem;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\AuthItem */
/* @var $form ticmakers\widgets\ActiveForm */

YiiAsset::register($this);
if (!$model->isNewRecord) {
	$items = Json::htmlEncode([
		'routes' => $modelRoutes
	]);
	$this->registerJs("var _items = {$items}; var _parent = '$model->name';");
	$this->registerJs($this->render('_script.js'));
	$animateIcon = ' <i class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></i>';
}
?>
<div class="row">

	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'name', ['help' => '', 'popover' => $model->getHelp('name')])->textInput(['maxlength' => true, 'tabindex' => 1]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'description', ['help' => '', 'popover' => $model->getHelp('description')])->textarea(['rows' => 4, 'tabindex' => 2]) ?>
	</div>

</div>

<?php if (!$model->isNewRecord) : ?>
	<div class="col-12 assignment-index">
		<fieldset style="display: flex;">
			<legend><?= Yii::t($model->module->id, 'Assignment') ?></legend>

			<div class="row w-100" style="justify-content: center">
				<div class="col-sm-5">
					<input class="form-control search" data-target="available" placeholder="<?= Yii::t($model->module->id, 'Search for available'); ?>">
					<select id="available-list" multiple size="20" class="form-control list" data-target="available">
					</select>
				</div>

				<div class="col-sm-1">
					<br><br>
					<?= Yii::$app->html::a('&gt;&gt;' . $animateIcon, ['auth-item-child/assign', 'id' => $model->name], [
						'class' => 'btn btn-success btn-assign',
						'data-target' => 'available',
						'title' => Yii::t($model->module->id, 'Assign'),
					]); ?><br><br>
					<?= Yii::$app->html::a('&lt;&lt;' . $animateIcon, ['auth-item-child/revoke', 'id' => $model->name], [
						'class' => 'btn btn-danger btn-assign',
						'data-target' => 'assigned',
						'title' => Yii::t($model->module->id, 'Remove'),
					]); ?>
				</div>

				<div class="col-sm-5">
					<input class="form-control search" data-target="assigned" placeholder="<?= Yii::t($model->module->id, 'Search for assigned'); ?>">
					<select id="assigned-list" multiple size="20" class="form-control list" data-target="assigned"></select>
				</div>
			</div>
		</fieldset>
	</div>
<?php endif; ?>
<?php
$this->registerCss('
	fieldset { 
		border:1px solid rgb(228, 234, 236); 
		border-radius: 3px; 
		padding: 10px  0 30px;
	}
	legend {  
		font-size:100%;
		border:none;		
		width: auto;
		border: 4px solid #fff;
	}
');
?>

src/views/auth-item/permissions/_form.php
<?php

use ticmakers\core\widgets\Tabs;
use ticmakers\core\widgets\ActiveForm;/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\AuthItem */
/* @var $form ticmakers\widgets\ActiveForm */
$form = ActiveForm::begin([
    'id' => 'auth-item-form',
]);

?>
<div class="auth-item-form">
    <?= Tabs::widget([
        'items' => [
            [
                'label'   => Yii::t($model->module->id, 'Información'),
                'content' => $this->render('1_information', ['form' => $form, 'model' => $model, 'modelRoutes' => !$model->isNewRecord ? $modelRoutes: []]),
                'active'  => true
            ],
        ],
    ]);
    ?>
    <br>
    <div class="form-group text-right">
        <?=  Yii::$app->ui::btnCancel(); ?>
        <?=  Yii::$app->ui::btnSend(null, ['form' => 'auth-item-form']); ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

src/views/auth-item/permissions/_search.php
<?php

use ticmakers\core\widgets\ActiveForm;
use ticmakers\adm\models\base\Users;
use ticmakers\adm\helpers\Strings;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\searchs\AuthItem */
/* @var $form ticmakers\widgets\ActiveForm */
?>

<div class="auth-item-search">
    <?php $form = ActiveForm::begin([
        'id'     => 'auth-item-search-form',
        'action' => ['permission'],
        'method' => 'get',
    ]); ?>

    <div class="row">
            
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'name',['help' => '','popover' => $model->getHelp('name')])->textInput(['tabindex' => 1, 'id' => 'name_search']) ?>

			</div>
			
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'description',['help' => '','popover' => $model->getHelp('description')])->textInput(['tabindex' => 3, 'id' => 'description_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'rule_name',['help' => '','popover' => $model->getHelp('rule_name')])->textInput(['tabindex' => 4, 'id' => 'rule_name_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'data',['help' => '','popover' => $model->getHelp('data')])->textInput(['tabindex' => 5, 'id' => 'data_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'active',['help' => '','popover' => $model->getHelp('active')])->widget(\kartik\widgets\Select2::classname(),
                        [
                            'data' => Yii::$app->strings::getCondition(),
                            'options' => ['placeholder' => Yii::$app->strings::getTextAll(), 'tabindex' => 6, 'id' => 'active_search'],
                        ]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'created_by',['help' => '','popover' => $model->getHelp('created_by')])->widget(\kartik\widgets\Select2::classname(),
                        ['data' => Users::getData(), 'options' => ['placeholder' => Yii::$app->strings::getTextEmpty(), 'tabindex' => 7, 'id' => 'created_by_search']]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'created_at',['help' => '','popover' => $model->getHelp('created_at')])->widget(\kartik\widgets\DatePicker::classname(), ['options' => ['tabindex' => 8, 'id' => 'created_at_search']]) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'updated_by',['help' => '','popover' => $model->getHelp('updated_by')])->widget(\kartik\widgets\Select2::classname(),
                        ['data' => Users::getData(), 'options' => ['placeholder' => Yii::$app->strings::getTextEmpty(), 'tabindex' => 9, 'id' => 'updated_by_search']]
                    ) ?>

			</div>

			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'updated_at',['help' => '','popover' => $model->getHelp('updated_at')])->widget(\kartik\widgets\DatePicker::classname(), ['options' => ['tabindex' => 8, 'id' => 'updated_at_search']]) ?>

			</div>
    </div>    <?php ActiveForm::end(); ?>
</div>

src/views/auth-item/permissions/create.php
<?php
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\AuthItem */

$breadcrumbs = [];
$this->params['breadcrumbs'] = [];
$this->title = Yii::t($model->module->id, 'Create permissions');

$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Permissions'), 'url' => ['auth-item/permission']];
$this->params['breadcrumbs'] = ArrayHelper::merge($this->params['breadcrumbs'], $breadcrumbs);
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Create')];
?>
<div class="auth-item-create">
    <?php echo $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

src/views/auth-item/permissions/index.php
<?php
use kartik\dynagrid\DynaGrid;
use ticmakers\core\base\Modal;
use kartik\grid\GridView;
use yii\helpers\Url;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel ticmakers\adm\models\searchs\AuthItem */
/* @var $dataProvider yii\data\ActiveDataProvider */

$breadcrumbs = [];
$this->params['breadcrumbs'] = [];
$this->title = Yii::t($searchModel->module->id, 'Permissions');
$this->params['breadcrumbs'][] = ['label' => Yii::t($searchModel->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'] = ArrayHelper::merge($this->params['breadcrumbs'], $breadcrumbs);
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-index">
        <?php echo DynaGrid::widget([
            'columns' => [
                ['class'=>'kartik\grid\SerialColumn'],
                				[
					'attribute' => 'name',
					'visible' => true,
				],
				/* [
					'attribute' => 'type',
					'visible' => true,
				], */
				[
					'attribute' => 'description',
					'format' => 'ntext',
					'visible' => true,
				],
				[
					'attribute' => 'rule_name',
					'visible' => false,
				],
				[
					'attribute' => 'data',
					'format' => 'ntext',
					'visible' => false,
				],
				[
					'attribute' => 'active',
					'visible' => false,
					'value' => function($model){
						return Yii::$app->strings::getCondition($model->active);
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => Yii::$app->strings::getCondition(),
					'filterInputOptions' => ['id' => 'active_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'created_by',
					'visible' => false,
					'value' => function($model){
						return $model->creadoPor->username;
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => []/* Yii::$app->userHelper::getUsers() */,
					'filterInputOptions' => ['id' => 'created_by_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'created_at',
					'visible' => false,
					'filterType' => GridView::FILTER_DATE,
					'filterInputOptions' => ['id' => 'created_at_grid'],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'updated_by',
					'visible' => false,
					'value' => function($model){
						return $model->modificadoPor->username;
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => []/* Yii::$app->userHelper::getUsers() */,
					'filterInputOptions' => ['id' => 'updated_by_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'updated_at',
					'visible' => false,
				],
                [
                    'class' => 'ticmakers\core\base\ActionColumn',
					'template' => '{update} {delete} {restore}',
					'buttons' => [
						'update' => function ($url, $model, $key) {
							
							$url = Url::to(['/adm/auth-item/update-permission', 'id' => $model->name]);
							if ($model->active == 'Y') {
								return Yii::$app->html::a(Yii::$app->html::iconFontAwesome(Yii::$app->html::ICON_PENCIL), $url, [
									'data-pjax' => 0,
									'title' => Yii::t($model->module->id, 'Editar')
								]);
							}
						},
					]
                ],
            ],
            'gridOptions' => [
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'toolbar' => [
                    '{toggleData}',
                    [
                        'content' =>
                        	Yii::$app->ui::btnNew('', ['create-permission']) . ' '
                            .Yii::$app->ui::btnSearch('') . ' '
                            .Yii::$app->ui::btnRefresh('', '/adm/auth-item/permission')
                    ],
                    '{dynagrid}',
                    '{export}',
                ],
                'pjax' => true,
                'options' => ['id' => 'gridview-auth-item'],
				'panelHeadingTemplate' => '<h3>' . (Yii::t($searchModel->module->id, $this->title)) . '</h3>'
            ],
            'options' => ['id' => 'dynagrid-auth-item'],
        ]) ?>
        </div>
<?php Modal::begin([
    'id'      => 'search-modal',
    'header'  => ''.Yii::t($searchModel->module->id, 'Búsqueda Avanzada'),
    'size'    => Modal::SIZE_LARGE,
    'footer' => Yii::$app->ui::btnCloseModal(Yii::t($searchModel->module->id, 'Cancelar'), Yii::$app->html::ICON_REMOVE) . Yii::$app->ui::btnSend(Yii::t($searchModel->module->id, 'Buscar'),  ['form' => 'auth-item-search-form']),
    'options' => [ 'style' => 'display: none;', 'tabindex' => false ]
]);
echo $this->render('_search', ['model' => $searchModel]);
Modal::end();
?>

src/views/auth-item/permissions/update.php
<?php
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\AuthItem */$breadcrumbs = [];
$this->params['breadcrumbs'] = [];
$this->title = Yii::t($model->module->id, 'Update') . ': ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Permissions'), 'url' => ['auth-item/permission']];
$this->params['breadcrumbs'][] = Yii::t($model->module->id, 'Update');
$this->params['breadcrumbs'] = ArrayHelper::merge($this->params['breadcrumbs'], $breadcrumbs);
?>
<div class="auth-item-update">
    <?php echo $this->render('_form', [
        'model' => $model,
        'modelRoutes' => $modelRoutes
    ]) ?>
</div>

src/views/auth-item/permissions/view.php
<?php

use ticmakers\helpers\Strings;

use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\AuthItem */

 $this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Auth Items'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="auth-item-view">

    <p>
        <?=  Yii::$app->ui::btnUpdate(null, ['update', 'id' => $model->name]); ?>
        <?=  Yii::$app->ui::btnDelete(null, ['delete', 'id' => $model->name]); ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'name',
            'type',
            'description:ntext',
            'rule_name',
            'data:ntext',
            [
                'attribute' => 'active',
                'value'     => Yii::$app->strings::getCondition($model->active),
            ],
            [
                'attribute' => 'created_by',
                'value'     => $model->creadoPor->username,
            ],
            'created_at',
            [
                'attribute' => 'updated_by',
                'value'     => $model->modificadoPor->username,
            ],
            'updated_at',
        ],
    ]) ?>

</div>