src/controllers/AuthAssignmentController.php
<?php

namespace ticmakers\adm\controllers;

use Yii;
use ticmakers\core\base\Controller;
use yii\web\Response;
use ticmakers\adm\models\base\AuthAssignment as AuthAssignment;
use ticmakers\adm\models\searchs\AuthAssignment as AuthAssignmentSearch;

/**
 * Controlador AuthAssignmentController implementa las acciones para el CRUD de el modelo AuthAssignment.
 *
 * @package ticmakers\adm
 * @subpackage controllers
 * @category Controllers
 *
 * @property string $model Ruta del modelo principal.
 * @property string $searchModel Ruta del modelo para la búsqueda.
 *
 * @author Juan Sebastian Muñoz Reyes <sebastianmr302@gmail.com>
 * @copyright Copyright (c) 2019 Tic Makers S.A.S. 
 * @version 0.0.1
 * @since 2.0.0
 */
class AuthAssignmentController extends Controller
{
    public $modelClass = AuthAssignment::class;
    public $searchModelClass = AuthAssignmentSearch::class;
    /**
     * Asignar rol(es) a un usuario y registrarlo
     * 
     * @param int $id | identificador del usuario  
     * @return array[] $roleList | listado de roles actualizado 
     */
    public function actionAssign($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $items = Yii::$app->getRequest()->post('items', []);
        $model = Yii::createObject($this->modelClass);
        return $model->assignItems($id, $items);
    }

    /**
     * Remover rol(es) a un usuario y registrarlo
     * 
     * @param int $id | identificador del usuario  
     * @return array[] $roleList | listado de roles actualizado 
     */
    public function actionRevoke($id)
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $items = Yii::$app->getRequest()->post('items', []);
        $model = Yii::createObject($this->modelClass);
        return $model->revokeItems($id, $items);
    }
}

src/controllers/UsersController.php
<?php

namespace ticmakers\adm\controllers;

use Yii;
use ticmakers\core\base\Controller;

use ticmakers\adm\models\base\AuthItem;
use ticmakers\adm\models\base\Users;
use ticmakers\adm\models\searchs\Users as UsersSearch;

/**
 * Controlador UsersController implementa las acciones para el CRUD de el modelo Users.
 *
 * @package ticmakers\adm
 * @subpackage controllers
 * @category Controllers
 *
 * @property string $model Ruta del modelo principal.
 * @property string $searchModel Ruta del modelo para la búsqueda.
 *
 * @author Juan Sebastian Muñoz Reyes <sebastianmr302@gmail.com>
 * @copyright Copyright (c) 2019 Tic Makers S.A.S. 
 * @version 0.0.1
 * @since 2.0.0
 */
class UsersController extends Controller
{
    public $modelClass = Users::class;
    public $searchModelClass = UsersSearch::class;
    /**
     * Permite visualizar el formulario para la creación de un registro
     * o realizar la validación de los datos enviados y crear el registro.
     *
     * @return string|Response
     */
    public function actionCreate()
    {
        $modelInstance = Yii::createObject($this->modelClass);
        $modelInstance->scenario = $modelInstance::SCENARIO_CREATE;
        if ($modelInstance->load(Yii::$app->request->post())) {
            if ($modelInstance->save()) {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t(
                    $modelInstance->module->id,
                    'It was created successfully.'
                ));
                return $this->redirect(['update', 'id' => $modelInstance->primaryKey]);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($modelInstance->module->id, 'An error occurred while trying to create.'));
            }
        }
        return $this->render('create', [
            'model' => $modelInstance,
        ]);
    }

    /**
     * Permite visualizar el formulario de actualización de un registro
     * o realizar la validación y modificación del registro.
     *
     * @param integer $id
     * @return string|Response
     */
    public function actionUpdate($id)
    {
        $modelInstance = $this->findModel($id);
        $modelInstance->scenario = $modelInstance::SCENARIO_UPDATE;
        $modelItems = [
            'available' => AuthItem::getAvailableItems($modelInstance->user_id),
            'assigned' => AuthItem::getAssignedItems($modelInstance->user_id)
        ];
        if ($modelInstance->load(Yii::$app->request->post())) {
            if ($modelInstance->save()) {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_SUCCESS, Yii::t($modelInstance->module->id, 'It was successfully edited.'));
                return $this->redirect(['index']);
            } else {
                Yii::$app->message::setMessage(Yii::$app->message::TYPE_DANGER, Yii::t($modelInstance->module->id, 'An error occurred while trying to edit.'));
            }
        }

        return $this->render('update', [
            'model' => $modelInstance,
            'modelItems' => $modelItems
        ]);
    }
}

src/views/users/1_information.php
<?php

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\Users */
/* @var $form ticmakers\widgets\ActiveForm */
?>

<div class="row">
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'username', ['help' => '', 'popover' => $model->getHelp('username')])->textInput(['maxlength' => true, 'tabindex' => 1]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'email', ['help' => '', 'popover' => $model->getHelp('email')])->textInput(['maxlength' => true, 'tabindex' => 2]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'password', ['help' => '', 'popover' => $model->getHelp('password')])->passwordInput(['maxlength' => true, 'tabindex' => 3]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'confirmPassword', ['help' => '', 'popover' => $model->getHelp('confirmPassword')])->passwordInput(['maxlength' => true, 'tabindex' => 4]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'confirmed_email', ['help' => '', 'popover' => $model->getHelp('confirmed_email')])->inline(true)->radioList(['Y' => Yii::t($model->module->id, 'Yes'), 'N' => Yii::t($model->module->id, 'No')], ['tabindex' => 5]) ?>
	</div>
	<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
		<?= $form->field($model, 'blocked', ['help' => '', 'popover' => $model->getHelp('blocked')])->inline(true)->radioList(['Y' => Yii::t($model->module->id, 'Yes'), 'N' => Yii::t($model->module->id, 'No')], ['tabindex' => 6]) ?>
	</div>

</div>
<br>
<div class="form-group text-right">
	<?= Yii::$app->ui::btnCancel(Yii::t($model->module->id, 'Cancel')); ?>
	<?= !$model->isNewRecord ? Yii::$app->html::button(
		'<i class="fa fa-arrow-right"></i> ' .
			Yii::t($model->module->id, 'Next'),
		['class' => 'btn btn-info', 'onclick' => "$('a[href=\"#w0-tab1\"]').click();"]
	) : ''; ?>
	<?= Yii::$app->ui::btnSend(Yii::t($model->module->id, 'Save'), ['form' => 'users-form']); ?>
</div>

src/views/users/2_assignment.php
<?php
/*
use mdm\admin\AnimateAsset; */

use yii\helpers\ArrayHelper;
use yii\helpers\Json;
use yii\web\YiiAsset;
use ticmakers\adm\models\base\AuthItem;
/* @var $this yii\web\View */
/* @var $model mdm\admin\models\Assignment */
/* @var $fullnameField string */

YiiAsset::register($this);

$items = Json::htmlEncode([
    'roles' => $modelItems,
]);

$this->registerJs("var _items = {$items};");
$this->registerJs($this->render('_script.js'));
$animateIcon = ' <i class="glyphicon glyphicon-refresh glyphicon-refresh-animate"></i>';
?>
<div class="assignment-index">

    <div class="row">
        <div class="col-sm-5">
            <input class="form-control search" data-target="available" placeholder="<?= Yii::t($model->module->id, 'Search for available'); ?>">
            <select id="available-list" multiple size="20" class="form-control list" data-target="available">
            </select>
        </div>

        <div class="col-sm-1">
            <br><br>
            <?= Yii::$app->html::a('&gt;&gt;' . $animateIcon, ['auth-assignment/assign', 'id' => $model->user_id], [
                'class' => 'btn btn-success btn-assign',
                'data-target' => 'available',
                'title' => Yii::t($model->module->id, 'Assign'),
            ]); ?><br><br>
            <?= Yii::$app->html::a('&lt;&lt;' . $animateIcon, ['auth-assignment/revoke', 'id' => $model->user_id], [
                'class' => 'btn btn-danger btn-assign',
                'data-target' => 'assigned',
                'title' => Yii::t($model->module->id, 'Remove'),
            ]); ?>
        </div>

        <div class="col-sm-5">
            <input class="form-control search" data-target="assigned" placeholder="<?= Yii::t($model->module->id, 'Search for assigned'); ?>">
            <select id="assigned-list" multiple size="20" class="form-control list" data-target="assigned">
            </select>
        </div>
    </div>
</div>
<br>
<div class="form-group text-right">
    <?= Yii::$app->ui::btnCancel(Yii::t($model->module->id, 'Cancel')); ?>
    <?= Yii::$app->html::button(
        '<i class="fa fa-arrow-left"></i> ' .
            Yii::t($model->module->id, 'Previous'),
        ['class' => 'btn btn-info', 'onclick' => "$('a[href=\"#w0-tab0\"]').click();"]
    ); ?>
    <?= Yii::$app->ui::btnSend(Yii::t($model->module->id, 'Save'), ['form' => 'users-form']); ?>
</div>

<?php

$this->registerCss('
.glyphicon-refresh-animate {
    -animation: spin .7s infinite linear;
    -ms-animation: spin .7s infinite linear;
    -webkit-animation: spinw .7s infinite linear;
    -moz-animation: spinm .7s infinite linear;
}

@keyframes spin {
    from { transform: scale(1) rotate(0deg);}
    to { transform: scale(1) rotate(360deg);}
}
  
@-webkit-keyframes spinw {
    from { -webkit-transform: rotate(0deg);}
    to { -webkit-transform: rotate(360deg);}
}

@-moz-keyframes spinm {
    from { -moz-transform: rotate(0deg);}
    to { -moz-transform: rotate(360deg);}
}');

?>

src/views/users/_form.php
<?php

use ticmakers\core\widgets\Tabs;
use ticmakers\core\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\Users */
/* @var $form ticmakers\widgets\ActiveForm */
$modelAssignment = new ticmakers\adm\models\base\AuthItem();
$form = ActiveForm::begin([
    'id' => 'users-form',
]);
?>
<div class="users-form">
    <?= Tabs::widget([
        'items' => [
            [
                'label'   => Yii::t($model->module->id, 'Information'),
                'content' => $this->render('1_information', ['form' => $form, 'model' => $model]),
                'active'  => true
            ],
            [
                'label'   => Yii::t($model->module->id, 'Assignments'),
                'content' => $this->render('2_assignment', ['model' => $model, 'modelItems' => !$model->isNewRecord ? $modelItems: []]),
                'linkOptions' => ['class' => $model->isNewRecord ? 'disabled' : ''],
            ],
        ],
    ]);
    ?>

    <?php ActiveForm::end(); ?>
</div>

src/views/users/_search.php
<?php

use ticmakers\core\widgets\ActiveForm;
use kartik\widgets\{Select2, DatePicker};
use ticmakers\adm\helpers\Strings;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\searchs\Users */
/* @var $form ticmakers\widgets\ActiveForm */
?>

<div class="users-search">
    <?php $form = ActiveForm::begin([
        'id'     => 'users-search-form',
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
            
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'username',['help' => '','popover' => $model->getHelp('username')])->textInput(['tabindex' => 1, 'id' => 'username_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'email',['help' => '','popover' => $model->getHelp('email')])->textInput(['tabindex' => 2, 'id' => 'email_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'password_hash',['help' => '','popover' => $model->getHelp('password_hash')])->textInput(['tabindex' => 3, 'id' => 'password_hash_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'auth_key',['help' => '','popover' => $model->getHelp('auth_key')])->textInput(['tabindex' => 4, 'id' => 'auth_key_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'password_reset_token',['help' => '','popover' => $model->getHelp('password_reset_token')])->textInput(['tabindex' => 5, 'id' => 'password_reset_token_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'email_key',['help' => '','popover' => $model->getHelp('email_key')])->textInput(['tabindex' => 6, 'id' => 'email_key_search']) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'confirmed_email',['help' => '','popover' => $model->getHelp('confirmed_email')])->widget(Select2::classname(),
					[
						'data' => Yii::$app->strings::getCondition(),
						'options' => ['placeholder' => Yii::$app->strings::getTextAll(), 'tabindex' => 7, 'id' => 'confirmed_email_search'],
					]
                ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'blocked',['help' => '','popover' => $model->getHelp('blocked')])->widget(Select2::classname(),
					[
						'data' => Yii::$app->strings::getCondition(),
						'options' => ['placeholder' => Yii::$app->strings::getTextAll(), 'tabindex' => 8, 'id' => 'blocked_search'],
					]
                )?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'accepted_terms',['help' => '','popover' => $model->getHelp('accepted_terms')])->widget(Select2::classname(),
                        [
                            'data' => Yii::$app->strings::getCondition(),
                            'options' => ['placeholder' => Yii::$app->strings::getTextAll(), 'tabindex' => 9, 'id' => 'accepted_terms_search'],
                        ]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'active',['help' => '','popover' => $model->getHelp('active')])->widget(Select2::classname(),
                        [
                            'data' => Yii::$app->strings::getCondition(),
                            'options' => ['placeholder' => Yii::$app->strings::getTextAll(), 'tabindex' => 10, 'id' => 'active_search'],
                        ]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'created_by',['help' => '','popover' => $model->getHelp('created_by')])->widget(Select2::classname(),
                        ['data' => ticmakers\adm\models\base\Users::getData(), 'options' => ['placeholder' => Yii::$app->strings::getTextEmpty(), 'tabindex' => 11, 'id' => 'created_by_search']]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'created_at',['help' => '','popover' => $model->getHelp('created_at')])->widget(DatePicker::classname(), ['options' => ['tabindex' => 12, 'id' => 'created_at_search']]) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
				<?= $form->field($model, 'updated_by',['help' => '','popover' => $model->getHelp('updated_by')])->widget(Select2::classname(),
                        ['data' => ticmakers\adm\models\base\Users::getData(), 'options' => ['placeholder' => Yii::$app->strings::getTextEmpty(), 'tabindex' => 13, 'id' => 'updated_by_search']]
                    ) ?>

			</div>
			<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

				<?= $form->field($model, 'updated_at',['help' => '','popover' => $model->getHelp('updated_at')])->widget(DatePicker::classname(), ['options' => ['tabindex' => 12, 'id' => 'updated_at_search']]) ?>

			</div>

    </div>    <?php ActiveForm::end(); ?>
</div>

src/views/users/create.php
<?php
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\Users */

$breadcrumbs = [];
$this->title = Yii::t( $model->module->id, 'Create');
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'][] = ['label' => Yii::t( $model->module->id, 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-create">
    <?php echo $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>

src/views/users/index.php
<?php
use kartik\dynagrid\DynaGrid;
use ticmakers\core\base\Modal;
use kartik\grid\GridView;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $searchModel ticmakers\adm\models\searchs\Users */
/* @var $dataProvider yii\data\ActiveDataProvider */

$breadcrumbs = [];
$this->params['breadcrumbs'] = [];
$this->title = Yii::t($searchModel->module->id, 'Users');
$this->params['breadcrumbs'][] = ['label' => Yii::t($searchModel->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'] = ArrayHelper::merge($this->params['breadcrumbs'], $breadcrumbs);
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="users-index">
        <?php echo DynaGrid::widget([
            'columns' => [
                ['class'=>'kartik\grid\SerialColumn'],
                				[
					'attribute' => 'user_id',
					'visible' => false,
				],
				[
					'attribute' => 'username',
					'visible' => true,
				],
				[
					'attribute' => 'email',
					'format' => 'email',
					'visible' => true,
				],
				[
					'attribute' => 'password_hash',
					'format' => 'ntext',
					'visible' => false,
				],
				[
					'attribute' => 'auth_key',
					'visible' => false,
				],
				[
					'attribute' => 'password_reset_token',
					'format' => 'ntext',
					'visible' => false,
				],
				[
					'attribute' => 'email_key',
					'format' => 'ntext',
					'visible' => false,
				],
				[
					'attribute' => 'confirmed_email',
					'format' => 'email',
					'visible' => false,
				],
				[
					'attribute' => 'blocked',
					'visible' => false,
				],
				[
					'attribute' => 'accepted_terms',
					'visible' => false,
				],
				[
					'attribute' => 'active',
					'visible' => false,
					'value' => function($model){
						return Yii::$app->strings::getCondition($model->active);
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => Yii::$app->strings::getCondition(),
					'filterInputOptions' => ['id' => 'active_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'created_by',
					'visible' => false,
					'value' => function($model){
						return $model->creadoPor->username;
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => ticmakers\adm\models\base\Users::getData(),
					'filterInputOptions' => ['id' => 'created_by_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'created_at',
					'visible' => true,
					'filterType' => GridView::FILTER_DATE,
					'filterInputOptions' => ['id' => 'created_at_grid'],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'updated_by',
					'visible' => false,
					'value' => function($model){
						return $model->modificadoPor->username;
					},
					'filterType' => GridView::FILTER_SELECT2,
					'filter' => ticmakers\adm\models\base\Users::getData(),
					'filterInputOptions' => ['id' => 'updated_by_grid', 'placeholder' => Yii::$app->strings::getTextAll()],
					'hiddenFromExport' => true,
				],
				[
					'attribute' => 'updated_at',
					'visible' => false,
				],
                [
                    'class' => 'ticmakers\core\base\ActionColumn',
                    
                ],
            ],
            'gridOptions' => [
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'toolbar' => [
                    '{toggleData}',
                    [
                        'content' =>
                        	Yii::$app->ui::btnNew('') . ' '
                            .Yii::$app->ui::btnSearch('') . ' '
                            .Yii::$app->ui::btnRefresh('')
                    ]
                ],
                'pjax' => true,
                'options' => ['id' => 'gridview-users'],
            ],
            'options' => ['id' => 'dynagrid-users'],
        ]) ?>
        </div>
<?php Modal::begin([
    'id'      => 'search-modal',
    'header'  => Yii::t($searchModel->module->id, 'Búsqueda Avanzada'),
    'size'    => Modal::SIZE_LARGE,
    'footer' => Yii::$app->ui::btnCloseModal(Yii::t($searchModel->module->id, 'Cancelar'), Yii::$app->html::ICON_REMOVE) . Yii::$app->ui::btnSend(Yii::t($searchModel->module->id, 'Buscar'),  ['form' => 'users-search-form']),
    'options' => [ 'style' => 'display: none;', 'tabindex' => false ]
]);
echo $this->render('_search', ['model' => $searchModel]);
Modal::end();
?>

src/views/users/update.php
<?php
use yii\helpers\ArrayHelper;
/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\Users */

$breadcrumbs = [];
$this->params['breadcrumbs'] = [];
$this->title = Yii::t( $model->module->id, 'Update') . ': ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Rbac'), 'url' => ['/adm']];
$this->params['breadcrumbs'][] = ['label' => Yii::t( $model->module->id, 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = Yii::t( $model->module->id, 'Update');
$this->params['breadcrumbs'][] = ['label' => $model->username];
$this->params['breadcrumbs'] = ArrayHelper::merge($this->params['breadcrumbs'], $breadcrumbs);
?>
<div class="users-update">
    <?php echo $this->render('_form', [
        'model' => $model,
        'modelItems' => $modelItems
    ]) ?>
</div>

src/views/users/view.php
<?php
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model ticmakers\adm\models\base\Users */

$this->title = $model->user_id;
$this->params['breadcrumbs'][] = ['label' => Yii::t($model->module->id, 'Users'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-view">

    <p>
        <?=  Yii::$app->ui::btnUpdate(null, ['update', 'id' => $model->user_id]); ?>
        <?=  Yii::$app->ui::btnDelete(null, ['delete', 'id' => $model->user_id]); ?>
    </p>
    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'user_id',
            'username',
            'email:email',
            'password_hash:ntext',
            'auth_key',
            'password_reset_token:ntext',
            'email_key:ntext',
            'confirmed_email:email',
            'blocked',
            'accepted_terms',
            [
                'attribute' => 'active',
                'value'     => ''/*  Yii::$app->strings::getCondition($model->active), */
            ],
            [
                'attribute' => 'created_by',
                'value'     => ''/* $model->creadoPor->username, */
            ],
            'created_at',
            [
                'attribute' => 'updated_by',
                'value'     => ''/* $model->modificadoPor->username */,
            ],
            'updated_at',
        ],
    ]) ?>

</div>